config/routes.rb
Rails.application.routes.draw do
  get '/pages', to: 'pages#dashboard'
  get '/pages/my_dogs', to: 'pages#my_dogs'
  get '/pages/my_bookings', to: 'pages#my_bookings'
  get '/pages/my_account', to: 'pages#my_account'

  resources :dogs do
    resources :bookings, except: [:index]
  end

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dog
  belongs_to :user

  validates :date, presence: true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  has_many :bookings


  validates :name, uniqueness: { scope: :user }
  validates :biography, :breed, :age, :good_with_children, presence: true
  validates :size, :walk, :energy, :friendly, presence: true, inclusion: { in: (1..10) }, numericality: { only_integer: true }

  def walk_length
    if self.walk < 4
      "Short walks"
    elsif self.walk < 7
      "Average walks"
    else
      "Long walks"
    end
  end

  def dog_size
    if self.size < 4
      "Small dog"
    elsif self.size < 7
      "Medium dog"
    else
      "Large dog"
    end
  end

  def dog_energy
    if self.energy < 4
      "Low"
    elsif self.energy < 7
      "Moderate"
    else
      "High"
    end
  end

  def dog_friendly
    if self.friendly < 4
      "Not good with others"
    elsif self.friendly < 7
      "Not sure how I feel about others"
    else
      "Loves others"
    end
  end

  def dog_gwc
    self.good_with_children ? "Yes" : "No"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dogs, dependent: :destroy
  has_many :bookings, dependent: :destroy

  has_one_attached :photo



  validates :first_name, :last_name, :address, presence: true
  validates :terms_and_conditions, acceptance: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :terms_and_conditions])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :address, :terms_and_conditions])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new
  end

  def create
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new(booking_params)
    @booking.dog = @dog
    @booking.user = current_user
    if @booking.save
      redirect_to dog_booking_path(@dog, @booking)
    else
      render :new
    end
  end

  def show
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.find(params[:id])
  end

  def edit
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to dog_booking_path(@dog, @booking)
  end

  def destroy
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dog_path(@dog)
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :dog, :user)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    sql_query = " \
            dogs.breed ILIKE :query \
            OR users.address ILIKE :query"

    if params[:query].present?
      @dogs = Dog.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @dogs = Dog.all
    end

    users = @dogs.map do |dog|
      [dog.user, dog]
    end

    @markers = []

    users.each do |user|
      @markers << {
        lat: user[0].latitude,
        lng: user[0].longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { dog: user[1] })
      }
    end
    # @markers = Dog.all.geocoded.map do |dog|
    #   {
    #     lat: dog.latitude,
    #     lng: dog.longitude,
    #     infoWindow: render_to_string(partial: "infowindow", locals: { dog: dog })
    #   }
    # end
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    if @dog.save
      redirect_to dog_path(@dog)
    else
      render :new
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    redirect_to dog_path(@dog)
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :biography, :breed, :age, :size,
                :good_with_children, :walk, :energy, :friendly, :user, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
  end

  def my_dogs
  end

  def my_bookings
  end

  def my_account
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@dog, @booking] do |f| %>
  <%= f.input :date, as: :string, input_html: { class: "datepicker"} %>
  <%= f.submit %>
<% end %>

app/views/bookings/edit.html.erb
<%= render 'form' %>

app/views/bookings/new.html.erb
<%= render 'form' %>

app/views/bookings/show.html.erb
<h1>
  <%= @dog.name %>
</h1>
<h2>
  <%= @dog.user.first_name %>
</h2>
<p><%= @booking.date %></p>
<%= link_to "Edit", edit_dog_booking_path(@dog, @booking) %><br>
<%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, dog_booking_path(@dog, @booking),
    method: :delete, data: { confirm: "Delete your booking with #{@dog.name}?" } %>

app/views/dogs/_form.html.erb
<div class="container">
  <div class="create-dog-background">
    <div class="create-dog-form">
      <div class="login-form-heading">
        <h3>Register Your Dog</h3>
      </div>
      <%= simple_form_for @dog do |f| %>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :photo, as: :file, label_html: { class: "dog-image-upload" } %>
        <%= f.input :biography, as: :text %>
        <%= f.input :breed %>
        <%= f.input :age %>
        <%= f.input :size, label: "How big is your dog?", as: :range, input_html: { min: 1, max: 10, class: "slider" }, required: false %>
        <div class="dog-slider-labels">
          <div class="label 1"><p>Small</p></div>
          <div class="label 2"><p>Medium</p></div>
          <div class="label 3"><p>Large</p></div>
        </div>
        <%= f.input :walk, label: "What length of walk does your dog like?", as: :range, input_html: { min: 1, max: 10, class: "slider" }, required: false %>
        <div class="dog-slider-labels">
          <div class="label 1"><p>10 mins</p></div>
          <div class="label 2"><p>1 hour</p></div>
          <div class="label 3"><p>2 hours +</p></div>
        </div>
        <%= f.input :energy, label: "How much energy does your dog have?", as: :range, input_html: { min: 1, max: 10, class: "slider" }, required: false %>
        <div class="dog-slider-labels">
          <div class="label 1"><p>Sleepy</p></div>
          <div class="label 2"><p>Ready to play or sit</p></div>
          <div class="label 3"><p>Needs attention</p></div>
        </div>
        <%= f.input :friendly, label: "How much energy does your dog have?", as: :range, input_html: { min: 1, max: 10, class: "slider" }, required: false %>
        <div class="dog-slider-labels">
          <div class="label 1"><p>Stay away from others!</p></div>
          <div class="label 2"><p>Not sure</p></div>
          <div class="label 3"><p>A natural socialite</p></div>
        </div>
        <%= f.input :good_with_children, as: :radio_buttons, collection: ['Yes', 'No'] %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Register Your Dog", class: "btn-login" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dogs/_infowindow.html.erb
<% if dog.photo.attached? %>
  <div class="#">
      <%= cl_image_tag dog.photo.key, height: 180, width: 270, crop: :fill %>
  </div>
<% end %>
<div class="mapboxgl-popup-content-stats">
  <div>
    <h2>
      <%= link_to dog_path(dog) do %>
        <%= dog.name %>
      <% end %>
    </h2>
    <span><%= dog.user.address %></span>
  </div>
  <div class="breed-stat">
    <i class="fas fa-dog"></i><br>
    <%= dog.breed %>
  </div>
</div>

app/views/dogs/edit.html.erb
<h1>Dogs#edit</h1>
<p>Find me  in app/views/dogs/edit.html.erb</p>
<%= render 'form' %>

app/views/dogs/index.html.erb
<div class="index-container">
  <div class="index-card-container">
    <% @dogs.each do |dog| %>
      <div class="index-card">
        <div>
          <% if dog.photo.attached? %>
            <div>
              <%= link_to dog_path(dog) do %>
                <%= cl_image_tag dog.photo.key, height: 180, width: 270, crop: :fill %>
              <% end %>
            </div>
          <% end %>
        </div>
        <div>
          <h2>
            <%= link_to dog.name, dog_path(dog) %>
          </h2>
          <p>
            <%= dog.biography[0..24] %>...
          </p>
          <div class="index-card-stats">
            <div class="stat">
              <i class="fas fa-dog"></i><br>
              <%= dog.breed %>
            </div>
            <div class="stat borders">
              <i class="fas fa-shoe-prints"></i><br>
              <%= dog.walk_length %>
            </div>
            <div class="stat">
              <i class="fas fa-ruler-horizontal"></i><br>
              <%= dog.dog_size %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div id="map"
     style="width: 100%; height: 100vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/dogs/new.html.erb
<div class="container">
  <div class="user-dog-card">
    <h2>Hi <%= current_user.first_name %></h2>
    <p>We care about matching personalities together, pup and person, so we need to take some information about your dog.</p>
    <br>
    <p>Whatever your reason for finding yourself here, be it needing a dog walker, someone to  look after the dogs when you go away or just wanting to bring some joy to those without a four legged friend, it all starts here.</p>
  </div>
  <%= render 'form' %>
</div>

app/views/dogs/show.html.erb
<div class="container">
<div class="dog-show-heading">
<h1><%= @dog.name %></h1>
<p class="dog-address"><%= @dog.user.address %></p>
</div>
<% if @dog.photo.attached? %>
  <div class="dog-image"><%= cl_image_tag @dog.photo.key, height: 800, width: 1140, crop: :fill %></div>
<% end %>
<div class="row">
<div class="dog-bio-heading col-8">
  <hr>
  <p><%= @dog.biography %></p>
  <p>Offered by <%= @dog.user.first_name %></p>
  <hr>
  <div class="dog-stats">
    <div>
    <div class=""><i class="fas fa-dog"></i> Breed: <%= @dog.breed %></div>
    <div><i class="fas fa-birthday-cake"></i> Age: <%= @dog.age %></div>
    <div><i class="fas fa-ruler-horizontal"></i> Size: <%= @dog.dog_size %></div>
    <div><i class="fas fa-shoe-prints"></i> Length of walk preference: <%= @dog.walk_length %></div>
    <div><i class="fas fa-bolt"></i> Energy level: <%= @dog.dog_energy %></div>
    <div><i class="fas fa-users"></i> Friendliness: <%= @dog.dog_friendly %></div>
    <div><i class="fas fa-child"></i> Good with children? <%= @dog.dog_gwc %></div>
  </div>
</div>
<div class="col-4 book">
  <%= link_to "Book this dog", new_dog_booking_path(@dog) %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogForADay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="min-height">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>
  <%= current_user.first_name %>'s Account
</h1>

<%= link_to "Dashboard", pages_path %>
<%= link_to "My Dogs", pages_my_dogs_path %>
<%= link_to "My Bookings", pages_my_bookings_path %>
<%= link_to "Account", pages_my_account_path %>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

app/views/pages/my_account.html.erb
<div class="container">
  <h1 class="underline">Hi <%= current_user.first_name%></h1>
    <div class="account_page_styling">
      <div class="account_card">
      <div class="user_navigation"><%= link_to "My Dashboard", pages_path %></div>
      <div class="user_navigation"><%= link_to "My Dogs", pages_my_dogs_path %></div>
      <div class="user_navigation"><%= link_to "My Bookings", pages_my_bookings_path %></div>
      <div id="is_active" class="user_navigation"><%= link_to "My Account", pages_my_account_path %><br></div>
    </div>
    <div class="container">
      <div class="account_details">
      <h2>Your Account Details</h2>
        <div class='box_container'>Biography:
                                    You don't have anything added :(</div>
        <div class='box_container'>First Name:  <%= current_user.first_name%></div>
        <div class='box_container'>Last Name:  <%= current_user.last_name %><br></div>
        <div class='box_container'>Email Address: <%= current_user.email %><br></div>
        <div class='box_container'>Address: <%= current_user.address %><br></div>
          <div class="btn-primary">
          <div class="edit_account"><%= link_to "Edit Account", edit_user_registration_path %></div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/my_bookings.html.erb
<h1>My Bookings</h1>

<%= link_to "Dashboard", pages_path %>
<%= link_to "My Dogs", pages_my_dogs_path %>
<%= link_to "My Bookings", pages_my_bookings_path %>
<%= link_to "Account", pages_my_account_path %>

<ul>
  <% current_user.bookings.each do |booking| %>
    <li>
      <%= booking.dog.name %> on <%= booking.date %> from <%= booking.dog.user.first_name %> <%= link_to "View this booking", dog_booking_path(booking.dog, booking) %>
    </li>
  <% end %>
</ul>

app/views/pages/my_dogs.html.erb
<h1>My Dogs</h1>

<%= link_to "Dashboard", pages_path %>
<%= link_to "My Dogs", pages_my_dogs_path %>
<%= link_to "My Bookings", pages_my_bookings_path %>
<%= link_to "Account", pages_my_account_path %>

<ul>
  <% current_user.dogs.each do |dog| %>
    <li>
      <%= dog.name %>
      <ul>
        <% dog.bookings.each do |booking| %>
          <li>
            <%= booking.date %> <%= link_to "View this booking", dog_booking_path(dog, booking) %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/shared/_banner.html.erb
<div id="home-banner">
  <div id="banner-content">
    <div id="banner-text">

      <%= image_tag "dog_banner.jpg", id: "home-banner-img" %>

      <h1>Dog for a Day - Friend for a Lifetime</h1>

      <p>
        Enter your city in the search bar above to be matched with lonely bitches in your area.
        Heavy petting is encouraged.
      </p>

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer-content">
 <div id="footer-icons">
    <i class="sm-icon fab fa-twitter fa-2x"></i>
    <i class="sm-icon fab fa-instagram fa-2x"></i>
    <i class="sm-icon fab fa-facebook-square fa-2x"></i>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-dfad">
  <h1 class="navbar-title"><%= link_to "Dog for a Day", root_path %> <i class="fas fa-dog nav-icon"></i></h1>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <div>
            <%= form_tag dogs_path, method: :get do %>
              <%= text_field_tag :query,
                params[:query]
              %>
              <%= submit_tag "Search", class: "btn search-btn" %>
            <% end %>
          </div>
        </li>
        <li class="nav-item">
          <button type="button" id="reg-dog-btn" class="btn"><%= link_to "Register your dog", new_dog_path %></button>
        </li>
        <li>
          <%= link_to pages_path do %>
            <%= image_tag "avatar.png", class: "avatar" %>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <div class="d-flex justify-content-center align-items-center h-100" id="navbarDropdown" data-toggle="dropdown"><i class="fas fa-bars fa-2x"></i></div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My account", pages_path, class: "dropdown-item" %>
            <%= link_to "My bookings", pages_my_bookings_path, class: "dropdown-item" %>
            <%= link_to "My dogs", pages_my_dogs_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= form_tag dogs_path, method: :get do %>
            <%= text_field_tag :query,
                params[:query],
                placeholder: "  Enter you city"
            %>
            <%= submit_tag "Search", class: "btn search-btn" %>
          <% end %>
        </li>
        <li class="nav-item">
          <button type="button" class="btn" id="reg-dog-btn"><%= link_to "Register your dog", new_user_session_path %></button>
        </li>
        <li class="nav-item">
          <button type="button" class="btn" id="login-btn"><%= link_to "Login", new_user_session_path %></button>
        </li>
      <% end %>
    </ul>
  </div>
</div>